name: Fetch and Build Skia

on:
  workflow_dispatch:

jobs:
  skia:
    name: Fetch and build Skia
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Python dependencies
        shell: pwsh
        run: |
          python -m pip install --upgrade pip

      - name: Clone depot_tools
        shell: pwsh
        run: |
          git clone --depth 1 https://chromium.googlesource.com/chromium/tools/depot_tools.git depot_tools
          Add-Content -Path $env:GITHUB_ENV -Value "PATH=${{ github.workspace }}\depot_tools;$env:PATH"

      - name: Fetch Skia sources
        shell: pwsh
        run: |
          fetch skia

      - name: Sync Skia dependencies
        shell: pwsh
        run: |
          cd skia
          python3 tools/git-sync-deps

      - name: Generate GN Build Files
        shell: pwsh
        run: |
          cd skia
          bin/gn gen out/Static --args='is_official_build=true skia_use_system_libjpeg_turbo=false'

      - name: Build Skia
        shell: pwsh
        run: |
          cd skia
          ninja -C out/Static
